const numberButton = document.querySelectorAll('[data-number]')
const operationButton = document.querySelectorAll('[data-operation]')
const equalsButton= document.querySelector('[data-equals]')
const deleteButton= document.querySelector('[data-delete]')
const allClearButton= document.querySelector('[data-all-clear]')
const previousOperandTextElementButton= document.querySelector('[data-previous-operand]')
const currentOperandTextElementButton= document.querySelector('[data-current-operand]')